name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compila
      id: compila
      uses: education/autograding-command-grader@v1
      with:
        test-name: Compila
        setup-command: ''
        command: "./mvnw clean compile"
        timeout: 10
        max-score: 5
    - name: Pruebas unitarias
      id: pruebas-unitarias
      uses: education/autograding-command-grader@v1
      with:
        test-name: Pruebas unitarias
        setup-command: "./mvnw test"
        command: gradle test
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        COMPILA_RESULTS: "${{steps.compila.outputs.result}}"
        PRUEBAS-UNITARIAS_RESULTS: "${{steps.pruebas-unitarias.outputs.result}}"
      with:
        runners: compila,pruebas-unitarias
